MANTENIMIENTO B3/Controllers/EmployeeController.cs
    using MANTENIMIENTO_B3.Data;
    using MANTENIMIENTO_B3.Models;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.EntityFrameworkCore;

    namespace MANTENIMIENTO_B3.Controllers
    {
        public class EmployeeController : Controller
        {
            private readonly ILogger<EmployeeController> _logger;
            private readonly AplicationDBContext _context;

            public EmployeeController(
               ILogger<EmployeeController> logger,
               AplicationDBContext context)
            {
                _logger = logger;
                _context = context;
            }

            public IActionResult Index()
            {
                var employees = _context.Employees.Include(e => e.TypeEmployee).AsNoTracking().ToList();
                ViewBag.Employees = employees;

                return View();
            }

            [HttpGet]
            public IActionResult Create()
            {
                var typeEmployees = _context.TypeEmployees.AsNoTracking().ToList();
                ViewBag.TypeEmployees = typeEmployees;
                return View();
            }

            [HttpPost]
            public IActionResult Save(Employee employee)
            {
                if (ModelState.IsValid)
                {
                    try
                    {
                        employee.FechaCreacion = DateTime.Now;
                        _context.Employees.Add(employee);
                        _context.SaveChanges();
                        return RedirectToAction("Index");
                    }
                    catch (Exception ex)
                    {
                        _logger.LogError(ex, "No se pudo guardar el empleado jovenazo.");
                        ModelState.AddModelError("", "Comunicate con el dueño.");
                    }
                }

                ViewBag.TypeEmployees = _context.TypeEmployees.AsNoTracking().ToList();
                return View("Create", employee);
            }

            [HttpGet]
            public IActionResult Edit(int id)
            {
                var employee = _context.Employees.Include(e => e.TypeEmployee).AsNoTracking().FirstOrDefault(x => x.Id == id);

                if (employee == null)
                {
                    return NotFound();
                }

                var typeEmployees = _context.TypeEmployees.AsNoTracking().ToList();
                ViewBag.TypeEmployees = typeEmployees;
                return View(employee);
            }

            [HttpPost]
            public IActionResult Update(Employee employee)
            {
                if (ModelState.IsValid)
                {
                    try
                    {
                        var existingEmployee = _context.Employees.FirstOrDefault(e => e.Id == employee.Id);

                        if (existingEmployee != null)
                        {
                            existingEmployee.Nombre = employee.Nombre;
                            existingEmployee.Apellido = employee.Apellido;
                            existingEmployee.Dui = employee.Dui;
                            existingEmployee.NumeroTelefonico = employee.NumeroTelefonico;
                            existingEmployee.TypeEmployeeId = employee.TypeEmployeeId;
                            existingEmployee.FechaModificacion = DateTime.Now;
                            existingEmployee.IsActive = employee.IsActive;

                            _context.Employees.Update(existingEmployee);
                            _context.SaveChanges();
                            return RedirectToAction("Index");
                        }
                    }
                    catch (Exception ex)
                    {
                        _logger.LogError(ex, "No se pudo actualizar el empleado jovenazo.");
                        ModelState.AddModelError("", "Comunicate con el dueño.");
                    }
                }

                ViewBag.TypeEmployees = _context.TypeEmployees.AsNoTracking().ToList();
                return View("Edit", employee);
            }

            [HttpGet]
            public IActionResult Delete(int id)
            {
                var employee = _context.Employees.AsNoTracking().FirstOrDefault(e => e.Id == id);
                if (employee == null)
                {
                    return NotFound();
                }
                return View(employee);
            }

            [HttpPost]
            public IActionResult DeleteConfirmed(int id)
            {
                try
                {
                    var employee = _context.Employees.Find(id);
                    if (employee != null)
                    {
                        _context.Employees.Remove(employee);
                        _context.SaveChanges();
                    }
                }
                catch (Exception ex)
                {
                    _logger.LogError(ex, "No se pudo borrar el empleado jovenazo.");
                    ModelState.AddModelError("", "Comunicate con el dueño.");
                    return View("Delete", id);
                }

                return RedirectToAction("Index");
            }
        }
    }

MANTENIMIENTO B3/Controllers/TypeEmployeeController.cs
using MANTENIMIENTO_B3.Data;
using MANTENIMIENTO_B3.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace MANTENIMIENTO_B3.Controllers
{
    public class TypeEmployeeController : Controller
    {
        private readonly ILogger<TypeEmployeeController> _logger;
        private readonly AplicationDBContext _context;

        public TypeEmployeeController(
           ILogger<TypeEmployeeController> logger,
           AplicationDBContext context)
        {
            _logger = logger;
            _context = context;
        }

        public IActionResult Index()
        {
            var typeemployees = _context.TypeEmployees.ToList();
            ViewBag.TypeEmployees = typeemployees;
            return View();
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Save(TypeEmployee typeemployee)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    typeemployee.FechaCreacion = DateTime.Now;
                    _context.Add(typeemployee);
                    _context.SaveChanges();
                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    _logger.LogError(ex, "No se pudo guardar el tipo de empleado jovenazo.");
                    ModelState.AddModelError("", "Comunicate con el dueño.");
                }
            }
            return View("Create", typeemployee);
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            var typeemployee = _context.TypeEmployees.Where(x => x.Id == id).FirstOrDefault();

            if (typeemployee == null)
            {
                return NotFound();
            }

            return View(typeemployee);
        }

        [HttpPost]
        public IActionResult Update(TypeEmployee typeemployee)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var existingTypeEmployee = _context.TypeEmployees.FirstOrDefault(e => e.Id == typeemployee.Id);

                    if (existingTypeEmployee != null)
                    {

                        existingTypeEmployee.FechaModificacion = DateTime.Now;

                        _context.TypeEmployees.Update(existingTypeEmployee);
                        _context.SaveChanges();
                        return RedirectToAction("Index");
                    }
                }
                catch (Exception ex)
                {
                    _logger.LogError(ex, "No se pudo actualizar el tipo de empleado jovenazo.");
                    ModelState.AddModelError("", "Comunicate con el dueño.");
                }
            }

            return View("Edit", typeemployee);
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            var typeemployee = _context.TypeEmployees.AsNoTracking().FirstOrDefault(e => e.Id == id);
            if (typeemployee == null)
            {
                return NotFound();
            }
            return View(typeemployee);
        }

        [HttpPost]
        public IActionResult DeleteConfirmed(int id)
        {
            try
            {
                var typeemployee = _context.TypeEmployees.Find(id);
                if (typeemployee != null)
                {
                    _context.TypeEmployees.Remove(typeemployee);
                    _context.SaveChanges();
                }
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "No se pudo borrar el tipo de empleado jovenazo.");
                ModelState.AddModelError("", "Comunicate con el dueño.");
                return View("Delete", id);
            }

            return RedirectToAction("Index");
        }
    }
}

MANTENIMIENTO B3/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MANTENIMIENTO_B3</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MANTENIMIENTO_B3.styles.css" asp-append-version="true" />
    @await RenderSectionAsync("Styles", required: false)
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MANTENIMIENTO_B3</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="Index">Empleado</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TypeEmployee" asp-action="Index">Tipo de Empleado</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - MANTENIMIENTO_B3 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>